# Generated by Django 4.2.6 on 2023-10-18 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
